#服务相关设置
server:
    port: 5122

#Spring相关设置
spring:
    #应用相关配置
    application:
        name:
            YQYQ Course Management
    #数据源相关配置
    datasource:
        url: jdbc:mariadb://118.24.3.84:3306/course_management?characterEncoding=utf8
        username: zhangbin
        password: zhangbin
        driver-class-name: org.mariadb.jdbc.Driver
    #Java持久化API相关配置
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDB10Dialect
        show-sql: true
    #静态资源路径相关配置
    resources:
        static-locations: classpath:static/,file:static/
    #模板引擎相关配置
    thymeleaf:
        cache: false
        enabled: true
        encoding: UTF-8
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html

#MyBatis相关配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
